# .github/workflows/stock_checker.yml
name: 'Myntra Stock Checker'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run stock check script
        env:
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
          VERIFIED_SENDER_EMAIL: ${{ secrets.VERIFIED_SENDER_EMAIL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python check_stock.py
      
      # --- ADD THIS NEW STEP AT THE END ---
      - name: Upload screenshot artifact
        if: always() # This ensures the screenshot is uploaded even if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug_screenshot.png
      # ------------------------------------
